# Generated by Django 4.1 on 2022-09-25 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_alter_watchlist_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='start_bid',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='listing',
            name='desc',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
