# Generated by Django 4.1 on 2022-09-25 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_listing_start_bid_alter_listing_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(blank=True, choices=[('books', 'Books'), ('bussiness', 'Business & Industrial'), ('clothing', 'Clothing, Shoes & Accessories'), ('collectibles', 'Collectibles'), ('electronics', 'Consumer Electronics'), ('crafts', 'Crafts'), ('dolls', 'Dolls & Bears'), ('home', 'Home & Garden'), ('motor', 'Motors'), ('pets', 'Pet Supplies'), ('sports', 'Sporting Goods'), ('mobile', 'Mobile Phones/Gadgets'), ('merch', 'Merchandise, Cards & Fan Shop'), ('toys', 'Toys & Hobbies'), ('antiques', 'Antiques'), ('computers', 'Computers/Tablets & Networking')], max_length=35, null=True),
        ),
    ]
