# Generated by Django 4.1 on 2023-01-31 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0010_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='color_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
