# Generated by Django 4.0.5 on 2023-02-01 07:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0011_listing_color_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Loyality',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('points', models.IntegerField(default=0)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loyality', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
